#!/bin/bash
# Technical Debt Scanner for NeuroForge
# Scans for TODO, FIXME, HACK markers

set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         🧼 TECHNICAL DEBT SCANNER v0.9.3 🧼                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Patterns to search for
PATTERNS="TODO|FIXME|HACK|XXX|DEPRECATED"

# Directories to exclude
EXCLUDE_DIRS="node_modules|build|dist|DerivedData|vendor|\.git|__pycache__|venv|\.venv|ml-fastvlm|artifacts|\.xcresult"

# Output file
OUTPUT_DIR="../releases/v0.9.3"
mkdir -p "$OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/DEBT_SCAN.md"

echo "📋 Scanning for debt markers: $PATTERNS"
echo ""

# Count total files scanned
TOTAL_FILES=$(git ls-files | grep -Ev "$EXCLUDE_DIRS" | wc -l | tr -d ' ')
echo "📁 Scanning $TOTAL_FILES files..."
echo ""

# Scan for markers
RESULTS=$(git ls-files | grep -Ev "$EXCLUDE_DIRS" | xargs grep -nHE "$PATTERNS" 2>/dev/null || true)

# Count occurrences
if [ -z "$RESULTS" ]; then
    echo -e "${GREEN}✅ No technical debt markers found!${NC}"
    echo ""
    
    # Write report
    cat > "$OUTPUT_FILE" <<EOF
# Technical Debt Scan Report

**Generated**: $(date -u +"%Y-%m-%d %H:%M UTC")  
**Version**: v0.9.3-dev  
**Files Scanned**: $TOTAL_FILES

---

## ✅ Results: CLEAN

No technical debt markers found!

**Patterns Searched**:
- TODO
- FIXME
- HACK
- XXX
- DEPRECATED

---

*Generated by: tools/debt_scanner.sh*
EOF
    
    echo "✅ Report written: $OUTPUT_FILE"
    exit 0
fi

# Count by type
TODO_COUNT=$(echo "$RESULTS" | grep -c "TODO" || echo "0")
FIXME_COUNT=$(echo "$RESULTS" | grep -c "FIXME" || echo "0")
HACK_COUNT=$(echo "$RESULTS" | grep -c "HACK" || echo "0")
XXX_COUNT=$(echo "$RESULTS" | grep -c "XXX" || echo "0")
DEPRECATED_COUNT=$(echo "$RESULTS" | grep -c "DEPRECATED" || echo "0")
TOTAL_COUNT=$(echo "$RESULTS" | wc -l | tr -d ' ')

echo -e "${YELLOW}⚠️  Found $TOTAL_COUNT debt markers:${NC}"
echo "  TODO: $TODO_COUNT"
echo "  FIXME: $FIXME_COUNT"
echo "  HACK: $HACK_COUNT"
echo "  XXX: $XXX_COUNT"
echo "  DEPRECATED: $DEPRECATED_COUNT"
echo ""

# Write detailed report
cat > "$OUTPUT_FILE" <<EOF
# Technical Debt Scan Report

**Generated**: $(date -u +"%Y-%m-%d %H:%M UTC")  
**Version**: v0.9.3-dev  
**Files Scanned**: $TOTAL_FILES  
**Markers Found**: $TOTAL_COUNT

---

## Summary

| Type | Count |
|------|-------|
| TODO | $TODO_COUNT |
| FIXME | $FIXME_COUNT |
| HACK | $HACK_COUNT |
| XXX | $XXX_COUNT |
| DEPRECATED | $DEPRECATED_COUNT |
| **TOTAL** | **$TOTAL_COUNT** |

---

## Details

EOF

# Add detailed results
echo "$RESULTS" | while IFS= read -r line; do
    FILE=$(echo "$line" | cut -d: -f1)
    LINE_NUM=$(echo "$line" | cut -d: -f2)
    CONTENT=$(echo "$line" | cut -d: -f3-)
    
    echo "**$FILE:$LINE_NUM**" >> "$OUTPUT_FILE"
    echo "\`\`\`" >> "$OUTPUT_FILE"
    echo "$CONTENT" >> "$OUTPUT_FILE"
    echo "\`\`\`" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
done

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Generated by: tools/debt_scanner.sh*" >> "$OUTPUT_FILE"

echo "✅ Report written: $OUTPUT_FILE"
echo ""

# Exit with warning code if debt found
if [ "$TOTAL_COUNT" -gt 0 ]; then
    echo -e "${YELLOW}⚠️  Technical debt found. Review DEBT_SCAN.md${NC}"
    exit 0  # Don't fail the build, just warn
else
    echo -e "${GREEN}✅ No technical debt found!${NC}"
    exit 0
fi

