#!/usr/bin/env python3
"""
Weekly Autopilot Report

Generates weekly summary of routing performance, breaker trips,
watchdog restarts, and overall system health.

Outputs to Athena Reporter (voice + window).

Usage:
    python3 scripts/weekly_autopilot_report.py
    
Cron:
    0 9 * * 1 cd ~/Documents/GitHub && python3 scripts/weekly_autopilot_report.py >> logs/weekly_reports.log 2>&1
"""

import os
import subprocess
import json
import urllib.parse
import urllib.request
import datetime as dt
import tempfile
import pathlib

PROM = os.getenv("PROM_URL", "http://127.0.0.1:9090")

def prom_query(query):
    """Query Prometheus"""
    url = f"{PROM}/api/v1/query?query=" + urllib.parse.quote(query)
    try:
        with urllib.request.urlopen(url, timeout=6) as r:
            return json.loads(r.read())["data"]["result"]
    except Exception as e:
        print(f"⚠️  Query failed: {e}")
        return []

def get_value(results, default=0.0):
    """Extract single value from Prometheus results"""
    if results and len(results) > 0:
        return float(results[0]["value"][1])
    return default

def main():
    """Generate weekly autopilot report"""
    print("📊 Generating weekly autopilot report...")
    
    # Query key metrics
    success_7d = prom_query('sum(increase(routing_success_total[7d]))/sum(increase(routing_decisions_total[7d]))')
    decisions_7d = prom_query('sum(increase(routing_decisions_total[7d]))')
    p95_latency = prom_query('histogram_quantile(0.95, sum(rate(routing_latency_ms_bucket[5m])) by (le))')
    promotions_7d = prom_query('sum(increase(trm_promotions_total[7d]))')
    breaker_trips = prom_query('sum(increase(breaker_trips_total[7d]))')
    active_alerts = prom_query('ALERTS{alertstate="firing"}')
    
    # Extract values
    success_rate = get_value(success_7d, 0.95)
    total_decisions = int(get_value(decisions_7d, 0))
    p95_ms = get_value(p95_latency, 0)
    promotions = int(get_value(promotions_7d, 0))
    trips = int(get_value(breaker_trips, 0))
    alerts = len([a for a in active_alerts if a.get("labels", {}).get("alertname") != "MonitoringDeadman"])
    
    # Determine status
    if success_rate < 0.90 or alerts > 0 or trips > 5:
        status_emoji = "🔥"
        status_text = "Attention Required"
    elif success_rate < 0.95 or p95_ms > 1500:
        status_emoji = "⚠️"
        status_text = "Degraded"
    else:
        status_emoji = "✅"
        status_text = "Nominal"
    
    # Generate synopsis
    summary = (
        f"Autopilot weekly report. Status {status_text}. "
        f"Seven day success rate {success_rate*100:.1f} percent. "
        f"{total_decisions} decisions. "
        f"P95 latency {p95_ms:.0f} milliseconds. "
    )
    
    if promotions > 0:
        summary += f"{promotions} model promotions. "
    
    if trips > 0:
        summary += f"{trips} breaker trips. "
    
    if alerts > 0:
        summary += f"{alerts} active alerts."
    
    # Generate detailed markdown
    now = dt.datetime.now()
    week_start = now - dt.timedelta(days=7)
    
    md = f"""# {status_emoji} Autopilot Weekly Report

**Week**: {week_start.strftime("%Y-%m-%d")} to {now.strftime("%Y-%m-%d")}  
**Generated**: {now.strftime("%Y-%m-%d %H:%M:%S")}

---

## 📊 Key Performance Indicators

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
| **Success Rate (7d)** | **{success_rate*100:.2f}%** | ≥95% | {'✅' if success_rate >= 0.95 else '⚠️'} |
| **Total Decisions** | **{total_decisions:,}** | >100 | {'✅' if total_decisions > 100 else '⚠️'} |
| **P95 Latency** | **{p95_ms:.0f} ms** | <1500ms | {'✅' if p95_ms < 1500 else '⚠️'} |
| **Model Promotions** | **{promotions}** | 1-3 | {'✅' if 1 <= promotions <= 3 else 'ℹ️'} |
| **Breaker Trips** | **{trips}** | <5 | {'✅' if trips < 5 else '⚠️'} |
| **Active Alerts** | **{alerts}** | 0 | {'✅' if alerts == 0 else '🔥'} |

---

## 🎯 Summary

**Status**: **{status_text}**

This week's routing system performance:
- Processed **{total_decisions:,}** routing decisions
- Achieved **{success_rate*100:.1f}%** success rate
- Maintained **{p95_ms:.0f}ms** p95 latency
"""
    
    if promotions > 0:
        md += f"\n🎓 **Evolution**: {promotions} model{'s' if promotions != 1 else ''} promoted this week\n"
    
    if trips > 0:
        md += f"\n🔴 **Stability**: {trips} circuit breaker trip{'s' if trips != 1 else ''} detected\n"
    
    if alerts > 0:
        md += f"\n🚨 **Alerts**: {alerts} active alert{'s' if alerts != 1 else ''} require attention\n"
    
    md += """

---

## 🔗 Quick Links

- [Grafana Dashboard](http://localhost:3001/d/trm-evolution)
- [Prometheus](http://localhost:9090)
- [Active Alerts](http://localhost:9093)

---

_Generated by Athena Autopilot • TRM Evolution Weekly Report_
"""
    
    # Open in Athena Reporter
    title = f"Autopilot Weekly Report - {status_emoji} {status_text}"
    
    # Write markdown to temp file
    tmp_file = pathlib.Path(tempfile.gettempdir()) / f"autopilot_weekly_{now.strftime('%Y%m%d')}.md"
    tmp_file.write_text(md, encoding="utf-8")
    
    # Generate report_id
    import hashlib
    h = hashlib.sha256()
    h.update(summary.encode("utf-8"))
    h.update(md.encode("utf-8"))
    report_id = h.hexdigest()[:16]
    
    # Build URL
    url = "athena://report?" + urllib.parse.urlencode({
        "title": title,
        "summary": summary,
        "md_path": str(tmp_file),
        "report_id": report_id,
        "ts": str(int(time.time()))
    }, quote_via=urllib.parse.quote)
    
    print(f"📢 Opening weekly report: {title}")
    print(f"📊 {summary[:100]}...")
    
    # Open reporter
    result = subprocess.run(["open", url], capture_output=True)
    
    if result.returncode != 0:
        print("⚠️  Reporter not available, printing to console:")
        print(md)
    else:
        print("✅ Report sent to Athena Reporter")

if __name__ == "__main__":
    import time
    main()

