#!/usr/bin/env python3
"""
DGM-AGI Core Bridge
Connects self-improving agents (DGM) with multi-agent system (AGI Core).

Flow:
1. DGM generates improved agent code
2. AGI Core reviews code (Scout expert)
3. AGI Core plans improvements (Plan expert)
4. AGI Core builds enhanced version (Build expert)
5. Result validated by governance
6. Deployed via canary system
"""

import asyncio
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class DGMAGIBridge:
    """
    Bridge connecting DGM self-improvement with AGI Core multi-agent system.
    
    Enables:
    - DGM-generated code reviewed by expert agents
    - Multi-agent enhancement of evolved agents
    - Governance oversight of combined system
    """
    
    def __init__(self):
        self.experts_dir = Path("experts")
        self.state_dir = Path("state/dgm_agi_integration")
        self.state_dir.mkdir(parents=True, exist_ok=True)
        
        self.expert_specialists = self._load_experts()
    
    def _load_experts(self) -> Dict:
        """Load AGI Core expert configurations."""
        experts = {}
        
        if not self.experts_dir.exists():
            return experts
        
        for expert_file in self.experts_dir.glob("*_expert.json"):
            expert_name = expert_file.stem.replace('_expert', '')
            
            try:
                with open(expert_file) as f:
                    experts[expert_name] = json.load(f)
                logger.debug(f"  ✓ Loaded expert: {expert_name}")
            except Exception as e:
                logger.warning(f"  ✗ Failed to load {expert_file}: {e}")
        
        return experts
    
    async def review_dgm_agent(self, agent_code: str, agent_metadata: Dict) -> Dict:
        """
        Have AGI Core experts review DGM-generated agent.
        
        Uses Scout→Plan→Build workflow:
        1. Scout: Analyze code quality, identify issues
        2. Plan: Suggest improvements
        3. Build: Apply enhancements
        
        Args:
            agent_code: Code generated by DGM
            agent_metadata: Performance and generation info
            
        Returns:
            Review results with enhancement suggestions
        """
        logger.info("🔍 AGI Core reviewing DGM agent...")
        
        review_results = {
            "agent_id": agent_metadata.get('agent_id'),
            "reviews": {},
            "enhancements": [],
            "consensus": None
        }
        
        # Phase 1: Scout - Code Analysis
        if 'scout' in self.expert_specialists:
            scout_review = await self._scout_analysis(agent_code, agent_metadata)
            review_results['reviews']['scout'] = scout_review
            logger.info(f"  ✓ Scout analysis: {scout_review.get('quality_score', 0):.2f}")
        
        # Phase 2: Plan - Enhancement Strategy
        if 'plan' in self.expert_specialists:
            plan_review = await self._plan_enhancements(agent_code, agent_metadata)
            review_results['reviews']['plan'] = plan_review
            review_results['enhancements'] = plan_review.get('suggestions', [])
            logger.info(f"  ✓ Plan: {len(review_results['enhancements'])} enhancements suggested")
        
        # Phase 3: Security Review
        if 'security' in self.expert_specialists:
            security_review = await self._security_analysis(agent_code)
            review_results['reviews']['security'] = security_review
            logger.info(f"  ✓ Security: {security_review.get('risk_level', 'unknown')}")
        
        # Phase 4: Performance Review
        if 'performance' in self.expert_specialists:
            perf_review = await self._performance_analysis(agent_code, agent_metadata)
            review_results['reviews']['performance'] = perf_review
            logger.info(f"  ✓ Performance: {perf_review.get('optimization_potential', 0):.1%}")
        
        # Consensus decision
        review_results['consensus'] = self._generate_consensus(review_results['reviews'])
        
        # Save review
        self._save_review(review_results)
        
        return review_results
    
    async def _scout_analysis(self, code: str, metadata: Dict) -> Dict:
        """Scout expert analyzes code quality."""
        # Simplified analysis
        lines = code.count('\n')
        has_comments = '#' in code or '"""' in code
        has_functions = 'def ' in code
        has_classes = 'class ' in code
        
        quality_score = 0.5
        if has_comments:
            quality_score += 0.1
        if has_functions:
            quality_score += 0.2
        if has_classes:
            quality_score += 0.1
        if 100 < lines < 500:
            quality_score += 0.1
        
        return {
            "expert": "scout",
            "quality_score": min(quality_score, 1.0),
            "code_lines": lines,
            "has_documentation": has_comments,
            "structure": {
                "functions": has_functions,
                "classes": has_classes
            },
            "issues": self._identify_code_issues(code)
        }
    
    def _identify_code_issues(self, code: str) -> List[str]:
        """Identify potential issues in code."""
        issues = []
        
        if len(code) > 10000:
            issues.append("Code is very long (>10k chars)")
        
        if 'TODO' in code or 'FIXME' in code:
            issues.append("Contains TODO/FIXME markers")
        
        if 'pass' in code and code.count('pass') > 3:
            issues.append("Multiple empty function bodies")
        
        return issues
    
    async def _plan_enhancements(self, code: str, metadata: Dict) -> Dict:
        """Plan expert suggests enhancements."""
        suggestions = []
        
        # Based on scout analysis
        if '#' not in code:
            suggestions.append({
                "type": "documentation",
                "priority": "medium",
                "description": "Add docstrings and comments"
            })
        
        if 'try:' not in code:
            suggestions.append({
                "type": "error_handling",
                "priority": "high",
                "description": "Add error handling with try/except"
            })
        
        if 'logging' not in code:
            suggestions.append({
                "type": "observability",
                "priority": "low",
                "description": "Add logging for debugging"
            })
        
        return {
            "expert": "plan",
            "suggestions": suggestions,
            "priority_count": {
                "high": sum(1 for s in suggestions if s['priority'] == 'high'),
                "medium": sum(1 for s in suggestions if s['priority'] == 'medium'),
                "low": sum(1 for s in suggestions if s['priority'] == 'low')
            }
        }
    
    async def _security_analysis(self, code: str) -> Dict:
        """Security expert analyzes code for vulnerabilities."""
        risks = []
        
        dangerous_patterns = [
            ('eval(', 'critical'),
            ('exec(', 'critical'),
            ('compile(', 'high'),
            ('os.system', 'critical'),
            ('subprocess', 'high'),
            ('pickle.load', 'high'),
            ('__import__', 'medium')
        ]
        
        for pattern, severity in dangerous_patterns:
            if pattern in code:
                risks.append({
                    "pattern": pattern,
                    "severity": severity,
                    "line": code.find(pattern)
                })
        
        risk_level = "low"
        if any(r['severity'] == 'critical' for r in risks):
            risk_level = "critical"
        elif any(r['severity'] == 'high' for r in risks):
            risk_level = "high"
        elif any(r['severity'] == 'medium' for r in risks):
            risk_level = "medium"
        
        return {
            "expert": "security",
            "risk_level": risk_level,
            "risks_found": len(risks),
            "risks": risks,
            "approved": len(risks) == 0
        }
    
    async def _performance_analysis(self, code: str, metadata: Dict) -> Dict:
        """Performance expert analyzes optimization potential."""
        optimizations = []
        
        # Check for potential optimizations
        if 'for ' in code and 'append(' in code:
            optimizations.append("Consider list comprehensions")
        
        if code.count('def ') > 10:
            optimizations.append("Consider class-based organization")
        
        if 'sleep(' in code:
            optimizations.append("Review async opportunities")
        
        current_perf = metadata.get('performance', 0.3)
        potential_improvement = len(optimizations) * 0.02  # 2% per optimization
        
        return {
            "expert": "performance",
            "current_performance": current_perf,
            "optimization_potential": potential_improvement,
            "suggestions": optimizations
        }
    
    def _generate_consensus(self, reviews: Dict) -> Dict:
        """Generate consensus from expert reviews."""
        # Security veto
        security = reviews.get('security', {})
        if security.get('risk_level') in ['critical', 'high']:
            return {
                "decision": "REJECT",
                "reason": "Security risks identified",
                "blocking_expert": "security"
            }
        
        # Quality check
        scout = reviews.get('scout', {})
        if scout.get('quality_score', 0) < 0.4:
            return {
                "decision": "NEEDS_IMPROVEMENT",
                "reason": "Code quality below threshold",
                "blocking_expert": "scout"
            }
        
        # Calculate combined score
        scores = []
        if 'scout' in reviews:
            scores.append(reviews['scout'].get('quality_score', 0.5))
        if 'performance' in reviews:
            perf = reviews['performance'].get('optimization_potential', 0)
            scores.append(min(0.5 + perf, 1.0))
        
        avg_score = sum(scores) / len(scores) if scores else 0.5
        
        if avg_score >= 0.7:
            return {
                "decision": "APPROVE",
                "confidence": avg_score,
                "reason": "Expert consensus positive"
            }
        elif avg_score >= 0.5:
            return {
                "decision": "APPROVE_WITH_CHANGES",
                "confidence": avg_score,
                "reason": "Acceptable with suggested improvements"
            }
        else:
            return {
                "decision": "NEEDS_IMPROVEMENT",
                "confidence": avg_score,
                "reason": "Below consensus threshold"
            }
    
    def _save_review(self, review: Dict):
        """Save review to state directory."""
        review_file = self.state_dir / f"review_{review['agent_id']}.json"
        
        with open(review_file, 'w') as f:
            json.dump({
                **review,
                "timestamp": datetime.now().isoformat()
            }, f, indent=2)
        
        logger.debug(f"  ✓ Review saved: {review_file}")
    
    async def enhance_dgm_agent(self, agent_code: str, review: Dict) -> str:
        """
        Apply AGI Core enhancements to DGM agent.
        
        Args:
            agent_code: Original DGM-generated code
            review: Review results from experts
            
        Returns:
            Enhanced agent code
        """
        enhancements = review.get('enhancements', [])
        
        if not enhancements:
            return agent_code
        
        logger.info(f"  🔧 Applying {len(enhancements)} enhancements...")
        
        enhanced_code = agent_code
        
        # Apply enhancements (simplified - would use foundation model)
        for enhancement in enhancements:
            if enhancement['type'] == 'documentation':
                enhanced_code = f'"""\nEnhanced DGM Agent\nAuto-generated documentation\n"""\n\n{enhanced_code}'
            
            elif enhancement['type'] == 'error_handling':
                # Wrap main functions in try/except
                enhanced_code = f"""
import logging
logger = logging.getLogger(__name__)

try:
{self._indent_code(enhanced_code, 4)}
except Exception as e:
    logger.error(f"Agent execution failed: {{e}}")
    raise
"""
            
            elif enhancement['type'] == 'observability':
                enhanced_code = f"import logging\nlogger = logging.getLogger(__name__)\n\n{enhanced_code}"
        
        return enhanced_code
    
    def _indent_code(self, code: str, spaces: int) -> str:
        """Indent code block."""
        indent = ' ' * spaces
        return '\n'.join(indent + line for line in code.split('\n'))
    
    async def integrated_evolution_step(
        self,
        dgm_orchestrator,
        agent_metadata: Dict
    ) -> Dict:
        """
        Run integrated evolution step combining DGM and AGI Core.
        
        1. DGM generates new agent
        2. AGI Core reviews and enhances
        3. Governance validates
        4. Deploy if approved
        
        Args:
            dgm_orchestrator: DGM orchestrator instance
            agent_metadata: Agent metadata from DGM
            
        Returns:
            Integration results
        """
        logger.info("🔄 Integrated Evolution Step")
        
        # Phase 1: DGM Generation
        logger.info("  Phase 1: DGM generates agent")
        dgm_agent_code = agent_metadata.get('code', '')
        
        # Phase 2: AGI Core Review
        logger.info("  Phase 2: AGI Core expert review")
        review = await self.review_dgm_agent(dgm_agent_code, agent_metadata)
        
        # Phase 3: Enhancement
        if review['consensus']['decision'] in ['APPROVE', 'APPROVE_WITH_CHANGES']:
            logger.info("  Phase 3: Applying enhancements")
            enhanced_code = await self.enhance_dgm_agent(dgm_agent_code, review)
        else:
            logger.warning(f"  Phase 3: Skipped (consensus: {review['consensus']['decision']})")
            enhanced_code = dgm_agent_code
        
        # Phase 4: Governance Validation
        logger.info("  Phase 4: Governance validation")
        # Would call governance adapter here
        
        result = {
            "dgm_generation": agent_metadata.get('generation'),
            "original_code_length": len(dgm_agent_code),
            "enhanced_code_length": len(enhanced_code),
            "review": review,
            "consensus": review['consensus'],
            "enhancement_applied": enhanced_code != dgm_agent_code,
            "timestamp": datetime.now().isoformat()
        }
        
        # Save integration result
        self._save_integration_result(result)
        
        return result
    
    def _save_integration_result(self, result: Dict):
        """Save integration result for analysis."""
        result_file = self.state_dir / f"integration_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        with open(result_file, 'w') as f:
            json.dump(result, f, indent=2)
    
    def get_integration_statistics(self) -> Dict:
        """Get statistics on DGM-AGI integrations."""
        results = []
        
        for result_file in self.state_dir.glob("integration_*.json"):
            with open(result_file) as f:
                results.append(json.load(f))
        
        if not results:
            return {"total": 0, "statistics": None}
        
        total = len(results)
        enhanced = sum(1 for r in results if r.get('enhancement_applied'))
        
        decisions = {}
        for r in results:
            decision = r.get('consensus', {}).get('decision', 'unknown')
            decisions[decision] = decisions.get(decision, 0) + 1
        
        return {
            "total": total,
            "enhanced": enhanced,
            "enhancement_rate": enhanced / total if total > 0 else 0,
            "consensus_decisions": decisions,
            "avg_review_experts": sum(len(r.get('review', {}).get('reviews', {})) for r in results) / total if total > 0 else 0
        }


# Example usage
async def example_integrated_evolution():
    """Example of integrated DGM-AGI evolution."""
    bridge = DGMAGIBridge()
    
    # Simulate DGM-generated agent
    dgm_agent = """
def solve_coding_task(problem_description):
    # DGM-generated solution
    solution = analyze_problem(problem_description)
    return solution
"""
    
    metadata = {
        "agent_id": "dgm_gen_42",
        "generation": 42,
        "performance": 0.35,
        "code": dgm_agent
    }
    
    # Run integrated review and enhancement
    result = await bridge.review_dgm_agent(dgm_agent, metadata)
    
    print(json.dumps(result, indent=2))
    
    # Show statistics
    stats = bridge.get_integration_statistics()
    print(f"\nIntegration Statistics:")
    print(f"  Total: {stats['total']}")
    print(f"  Enhancement Rate: {stats.get('enhancement_rate', 0):.1%}")


if __name__ == "__main__":
    asyncio.run(example_integrated_evolution())

