#!/bin/bash
# Metrics Summary Generator for NeuroForge
# Captures GitHub Insights and system metrics

set -euo pipefail

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║         📈 METRICS SUMMARY GENERATOR v0.9.3 📈               ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""

# Output
OUTPUT_DIR="../releases/v0.9.3"
mkdir -p "$OUTPUT_DIR"
OUTPUT_FILE="$OUTPUT_DIR/METRICS_SUMMARY.md"

# Header
cat > "$OUTPUT_FILE" <<EOF
# Metrics Summary Report

**Generated**: $(date -u +"%Y-%m-%d %H:%M UTC")  
**Version**: v0.9.3-dev

---

## Git Repository Metrics

EOF

# Git stats
echo "📊 Collecting git metrics..."

COMMIT_COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "N/A")
BRANCH_COUNT=$(git branch -a 2>/dev/null | wc -l | tr -d ' ')
TAG_COUNT=$(git tag | wc -l | tr -d ' ')
CONTRIBUTOR_COUNT=$(git shortlog -sn --all | wc -l | tr -d ' ')

cat >> "$OUTPUT_FILE" <<EOF
| Metric | Value |
|--------|-------|
| Total Commits | $COMMIT_COUNT |
| Branches | $BRANCH_COUNT |
| Tags | $TAG_COUNT |
| Contributors | $CONTRIBUTOR_COUNT |

### Recent Activity (Last 7 Days)

EOF

# Recent commits
RECENT_COMMITS=$(git log --since="7 days ago" --oneline | wc -l | tr -d ' ')
echo "- Commits: $RECENT_COMMITS" >> "$OUTPUT_FILE"

# Recent contributors
RECENT_CONTRIBUTORS=$(git shortlog -sn --since="7 days ago" | wc -l | tr -d ' ')
echo "- Active Contributors: $RECENT_CONTRIBUTORS" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Eval metrics
cat >> "$OUTPUT_FILE" <<EOF
## Eval Metrics

EOF

if curl -s http://localhost:8788/eval/fixtures 2>/dev/null | grep -q "ticket"; then
    FIXTURE_COUNT=$(curl -s http://localhost:8788/eval/fixtures 2>/dev/null | jq '.fixtures | length' || echo "N/A")
    echo "- Total Fixtures: $FIXTURE_COUNT" >> "$OUTPUT_FILE"
    echo "- Last Run: Check eval API at http://localhost:8788" >> "$OUTPUT_FILE"
else
    echo "- Eval API: Not running (start with: make eval-api)" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# RAG metrics
cat >> "$OUTPUT_FILE" <<EOF
## RAG Service Metrics

EOF

if curl -s http://localhost:8015/api/rag/health 2>/dev/null | grep -q "healthy"; then
    TRANSCRIPT_COUNT=$(curl -s http://localhost:8015/api/rag/health 2>/dev/null | jq '.transcripts' || echo "N/A")
    echo "- Transcripts Indexed: $TRANSCRIPT_COUNT" >> "$OUTPUT_FILE"
    echo "- Status: Healthy ✅" >> "$OUTPUT_FILE"
else
    echo "- RAG Service: Not running" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# CI/CD metrics
cat >> "$OUTPUT_FILE" <<EOF
## CI/CD Metrics

### Workflows
- ui-golden.yml: PR golden diff (visual regression)
- qa-sweep.yml: Full QA on main push
- services-health.yml: Service monitoring (every 6h)
- eval.yml: SLA enforcement (80% threshold)

### Quality Gates
- Pre-push QA hook: ✅ Active
- Golden diff: ✅ Active  
- Eval SLA: ✅ 80% threshold
- Service health: ✅ Every 6h

EOF

# GitHub CLI metrics (if available)
if command -v gh &> /dev/null; then
    echo "### GitHub Repository Stats" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    
    OPEN_ISSUES=$(gh issue list --state open 2>/dev/null | wc -l | tr -d ' ' || echo "N/A")
    CLOSED_ISSUES=$(gh issue list --state closed --limit 100 2>/dev/null | wc -l | tr -d ' ' || echo "N/A")
    OPEN_PRS=$(gh pr list --state open 2>/dev/null | wc -l | tr -d ' ' || echo "N/A")
    MERGED_PRS=$(gh pr list --state merged --limit 50 2>/dev/null | wc -l | tr -d ' ' || echo "N/A")
    
    echo "- Open Issues: $OPEN_ISSUES" >> "$OUTPUT_FILE"
    echo "- Closed Issues (last 100): $CLOSED_ISSUES" >> "$OUTPUT_FILE"
    echo "- Open PRs: $OPEN_PRS" >> "$OUTPUT_FILE"
    echo "- Merged PRs (last 50): $MERGED_PRS" >> "$OUTPUT_FILE"
fi

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Footer
cat >> "$OUTPUT_FILE" <<EOF
## Notes

- Git metrics: From repository history
- Eval metrics: From running eval API (port 8788)
- RAG metrics: From running RAG service (port 8015)
- CI/CD metrics: From .github/workflows/

**View live metrics**:
- Dashboard: http://localhost:8787
- Eval API: http://localhost:8788
- RAG API: http://localhost:8015

---

*Generated by: tools/metrics_summary.sh*
EOF

echo "✅ Metrics summary written: $OUTPUT_FILE"
echo ""
echo "📊 Summary:"
echo "  Commits: $COMMIT_COUNT"
echo "  Tags: $TAG_COUNT"
echo "  Recent activity (7d): $RECENT_COMMITS commits"

exit 0

