"""
Provider Registry for Research Implementations
==============================================
Central registry for all capability providers including new research implementations
"""

from typing import Dict, List
from dataclasses import dataclass


@dataclass
class ProviderInfo:
    """Information about a registered provider"""
    name: str
    module_path: str
    capabilities: List[str]
    description: str
    enabled: bool = True
    experimental: bool = False


# Registry of all providers
PROVIDERS: Dict[str, ProviderInfo] = {
    # Core providers
    "capability_stub": ProviderInfo(
        name="Capability Stub",
        module_path="orchestrator.providers.capability_stub",
        capabilities=["chat", "summarize"],
        description="Basic capability stub for testing",
        enabled=True,
        experimental=False
    ),

    # Research implementations - Generated by autonomous system
    "contextual_thompson_sampling": ProviderInfo(
        name="Contextual Thompson Sampling",
        module_path="orchestrator.providers.contextual_thompson_sampling",
        capabilities=["bandit", "decision_making", "context_aware_routing"],
        description="Neural network enhanced Thompson Sampling with context features",
        enabled=True,
        experimental=True
    ),

    "adaptive_prompts": ProviderInfo(
        name="Adaptive Prompt Optimizer",
        module_path="orchestrator.providers.adaptive_prompts",
        capabilities=["prompt_optimization", "reinforcement_learning"],
        description="RL-based automatic prompt optimization from task performance",
        enabled=True,
        experimental=True
    ),

    "statistical_rollout": ProviderInfo(
        name="Statistical Planning",
        module_path="orchestrator.providers.statistical_rollout",
        capabilities=["planning", "monte_carlo", "simulation"],
        description="Monte Carlo Tree Search for action selection",
        enabled=True,
        experimental=True
    ),

    "uncertainty_estimation": ProviderInfo(
        name="Uncertainty Estimator",
        module_path="orchestrator.providers.uncertainty_estimation",
        capabilities=["uncertainty", "confidence", "risk_assessment"],
        description="Bayesian uncertainty estimation using MC Dropout",
        enabled=True,
        experimental=True
    ),

    "meta_learning": ProviderInfo(
        name="Meta-Learner",
        module_path="orchestrator.providers.meta_learning",
        capabilities=["few_shot_learning", "rapid_adaptation", "transfer_learning"],
        description="MAML-style meta-learning for rapid task adaptation",
        enabled=True,
        experimental=True
    ),
}


def get_provider(provider_id: str) -> ProviderInfo:
    """Get provider info by ID"""
    if provider_id not in PROVIDERS:
        raise ValueError(f"Unknown provider: {provider_id}")
    return PROVIDERS[provider_id]


def get_providers_by_capability(capability: str) -> List[ProviderInfo]:
    """Get all providers that support a given capability"""
    return [
        info for info in PROVIDERS.values()
        if capability in info.capabilities and info.enabled
    ]


def list_all_providers() -> Dict[str, ProviderInfo]:
    """Get all registered providers"""
    return PROVIDERS.copy()


def list_experimental_providers() -> Dict[str, ProviderInfo]:
    """Get all experimental/research providers"""
    return {
        pid: info for pid, info in PROVIDERS.items()
        if info.experimental and info.enabled
    }
