"""
STOP Optimizer - Self-Taught Optimization for AGI Core

Implements the Self-Taught Optimizer (STOP) approach from:
https://arxiv.org/abs/2310.02304

Key Concepts:
- Scaffolding programs that improve themselves
- Multiple optimization strategies (beam search, genetic algorithms, simulated annealing)
- LLM-generated improvement candidates
- Utility function-driven selection
- Sandboxed execution for safety
"""

import os
import time
import json
import hashlib
import subprocess
from typing import Dict, List, Any, Optional, Callable, Tuple
from pathlib import Path
from dataclasses import dataclass, asdict
from enum import Enum
import tempfile
import ast

import logging
logger = logging.getLogger(__name__)

from .evaluation_metrics import (
    MetricsCollector,
    PerformanceMetrics,
    UtilityFunction,
    get_metrics_collector
)


class OptimizationStrategy(Enum):
    """Optimization strategies for STOP"""
    BEAM_SEARCH = "beam_search"
    GENETIC_ALGORITHM = "genetic_algorithm"
    SIMULATED_ANNEALING = "simulated_annealing"
    RANDOM_SEARCH = "random_search"
    HILL_CLIMBING = "hill_climbing"


@dataclass
class OptimizationCandidate:
    """A candidate improvement generated by STOP"""
    candidate_id: str
    strategy: OptimizationStrategy
    code: str
    utility_score: float
    generation: int
    parent_id: Optional[str] = None
    metadata: Dict[str, Any] = None
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["strategy"] = self.strategy.value
        return data


@dataclass
class OptimizationResult:
    """Result of a STOP optimization run"""
    optimization_id: str
    target_function: str
    strategy: OptimizationStrategy
    iterations: int
    candidates_generated: int
    best_candidate: OptimizationCandidate
    baseline_utility: float
    improved_utility: float
    improvement_percent: float
    duration_seconds: float
    confidence_score: float
    timestamp: float
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["strategy"] = self.strategy.value
        data["best_candidate"] = self.best_candidate.to_dict()
        return data


class LLMInterface:
    """
    Interface for LLM code generation
    
    Supports both local models and cloud APIs:
    - Local: Ollama, LM Studio, vLLM, etc.
    - Cloud: OpenAI, Anthropic, etc.
    """
    
    def __init__(
        self,
        model: str = "codellama:7b",
        api_base: Optional[str] = None,
        api_key: Optional[str] = None,
        use_local: bool = True
    ):
        self.model = model
        self.use_local = use_local
        
        if use_local:
            # Default to Ollama endpoint
            self.api_base = api_base or os.getenv("OLLAMA_API_BASE", "http://localhost:11434")
            self.enabled = True
            logger.info(f"LLM interface initialized: local model '{model}' at {self.api_base}")
        else:
            # Cloud API (OpenAI, etc.)
            self.api_base = api_base or "https://api.openai.com/v1"
            self.api_key = api_key or os.getenv("OPENAI_API_KEY")
            self.enabled = bool(self.api_key)
            
            if not self.enabled:
                logger.warning("LLM interface disabled - no API key provided for cloud models")
            else:
                logger.info(f"LLM interface initialized: cloud model '{model}'")
    
    def generate_improvement(
        self,
        original_code: str,
        utility_function_description: str,
        context: Dict[str, Any],
        strategy: OptimizationStrategy
    ) -> str:
        """
        Generate an improved version of the code using local or cloud LLM
        """
        if not self.enabled:
            return self._simulate_improvement(original_code, strategy)
        
        # Build prompt
        prompt = self._build_prompt(original_code, utility_function_description, context, strategy)
        
        try:
            if self.use_local:
                return self._call_local_llm(prompt)
            else:
                return self._call_cloud_llm(prompt)
        except Exception as e:
            logger.error(f"LLM call failed: {e}, using simulated improvement")
            return self._simulate_improvement(original_code, strategy)
    
    def _call_local_llm(self, prompt: str) -> str:
        """
        Call local LLM (Ollama, LM Studio, etc.)
        
        Supports Ollama API format
        """
        import requests
        
        try:
            # Ollama API endpoint
            url = f"{self.api_base}/api/generate"
            
            payload = {
                "model": self.model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.7,
                    "top_p": 0.9,
                    "num_predict": 1024
                }
            }
            
            response = requests.post(url, json=payload, timeout=60)
            response.raise_for_status()
            
            result = response.json()
            generated_code = result.get("response", "")
            
            # Extract code from markdown if present
            if "```python" in generated_code:
                start = generated_code.find("```python") + 9
                end = generated_code.find("```", start)
                generated_code = generated_code[start:end].strip()
            
            logger.debug(f"Generated code from local LLM ({len(generated_code)} chars)")
            return generated_code
            
        except Exception as e:
            logger.error(f"Local LLM call failed: {e}")
            raise
    
    def _call_cloud_llm(self, prompt: str) -> str:
        """
        Call cloud LLM (OpenAI, Anthropic, etc.)
        
        Uses OpenAI API format
        """
        try:
            import openai
            
            openai.api_key = self.api_key
            openai.api_base = self.api_base
            
            response = openai.ChatCompletion.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert code optimizer."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                max_tokens=1024
            )
            
            generated_code = response.choices[0].message.content
            
            # Extract code from markdown if present
            if "```python" in generated_code:
                start = generated_code.find("```python") + 9
                end = generated_code.find("```", start)
                generated_code = generated_code[start:end].strip()
            
            logger.debug(f"Generated code from cloud LLM ({len(generated_code)} chars)")
            return generated_code
            
        except Exception as e:
            logger.error(f"Cloud LLM call failed: {e}")
            raise
    
    def _simulate_improvement(self, original_code: str, strategy: OptimizationStrategy) -> str:
        """
        Simulate code improvement for testing
        
        This is a placeholder - in production, use actual LLM generation.
        """
        # For simulation, just add a comment about the optimization strategy
        lines = original_code.split('\n')
        comment = f"    # Optimized using {strategy.value}"
        
        # Insert comment after function definition
        for i, line in enumerate(lines):
            if 'def ' in line:
                lines.insert(i + 1, comment)
                break
        
        return '\n'.join(lines)
    
    def _build_prompt(
        self,
        original_code: str,
        utility_description: str,
        context: Dict[str, Any],
        strategy: OptimizationStrategy
    ) -> str:
        """Build prompt for LLM code generation"""
        return f"""You are an expert code optimizer. Your task is to improve the following Python function.

Original Code:
```python
{original_code}
```

Optimization Goal:
{utility_description}

Context:
{json.dumps(context, indent=2)}

Strategy: {strategy.value}

Instructions:
1. Analyze the code for optimization opportunities
2. Apply {strategy.value} optimization approach
3. Maintain functional correctness
4. Improve performance, efficiency, or code quality
5. Return ONLY the improved Python code, no explanations

Generate the improved version:
"""


class SandboxExecutor:
    """
    Sandboxed execution environment for testing candidate improvements
    
    Provides isolation and safety for running untrusted code.
    """
    
    def __init__(self, timeout_seconds: int = 5):
        self.timeout_seconds = timeout_seconds
    
    def execute(
        self,
        code: str,
        test_inputs: List[Any],
        expected_behavior: Optional[Callable] = None
    ) -> Tuple[bool, float, Optional[str]]:
        """
        Execute code in sandbox and measure performance
        
        Returns:
            (success, execution_time_ms, error_message)
        """
        try:
            # Create temporary file for code
            with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False) as f:
                f.write(code)
                code_file = f.name
            
            # Execute in subprocess with timeout
            start_time = time.time()
            
            result = subprocess.run(
                ['python3', code_file],
                capture_output=True,
                text=True,
                timeout=self.timeout_seconds
            )
            
            execution_time_ms = (time.time() - start_time) * 1000
            
            # Cleanup
            os.unlink(code_file)
            
            # Check for errors
            if result.returncode != 0:
                return False, execution_time_ms, result.stderr
            
            # Validate behavior if checker provided
            if expected_behavior:
                try:
                    # Parse and validate output
                    output = result.stdout
                    if not expected_behavior(output):
                        return False, execution_time_ms, "Output validation failed"
                except Exception as e:
                    return False, execution_time_ms, f"Validation error: {e}"
            
            return True, execution_time_ms, None
            
        except subprocess.TimeoutExpired:
            return False, self.timeout_seconds * 1000, "Execution timeout"
        except Exception as e:
            return False, 0.0, str(e)
    
    def validate_syntax(self, code: str) -> Tuple[bool, Optional[str]]:
        """Validate Python syntax without executing"""
        try:
            ast.parse(code)
            return True, None
        except SyntaxError as e:
            return False, str(e)


class STOPOptimizer:
    """
    Self-Taught Optimizer (STOP)
    
    Implements recursive self-improvement for code optimization.
    Uses LLM to generate improvement candidates and utility functions
    to evaluate them.
    
    Based on: https://arxiv.org/abs/2310.02304
    """
    
    def __init__(
        self,
        metrics_collector: Optional[MetricsCollector] = None,
        llm_interface: Optional[LLMInterface] = None,
        sandbox: Optional[SandboxExecutor] = None
    ):
        self.metrics = metrics_collector or get_metrics_collector()
        self.llm = llm_interface or LLMInterface()
        self.sandbox = sandbox or SandboxExecutor()
        
        # Storage
        self.state_dir = Path("./state/stop_optimizer")
        self.state_dir.mkdir(parents=True, exist_ok=True)
        
        # History
        self.optimization_history: List[OptimizationResult] = []
        
        logger.info("STOPOptimizer initialized")
    
    def optimize(
        self,
        target_code: str,
        utility_function: Callable[[Dict[str, Any]], float],
        utility_description: str,
        strategy: OptimizationStrategy = OptimizationStrategy.BEAM_SEARCH,
        iterations: int = 10,
        beam_width: int = 3,
        context: Optional[Dict[str, Any]] = None
    ) -> OptimizationResult:
        """
        Run STOP optimization on target code
        
        Args:
            target_code: Original code to optimize
            utility_function: Function that scores candidates (0-1, higher is better)
            utility_description: Description of what to optimize for
            strategy: Optimization strategy to use
            iterations: Number of optimization iterations
            beam_width: Width of beam search (candidates per generation)
            context: Additional context for optimization
        
        Returns:
            OptimizationResult with best candidate and metrics
        """
        optimization_id = f"stop_{int(time.time())}_{hashlib.md5(target_code.encode()).hexdigest()[:8]}"
        start_time = time.time()
        
        logger.info(f"Starting STOP optimization: {optimization_id}, strategy={strategy.value}, iterations={iterations}")
        
        # Validate syntax of original code
        valid, error = self.sandbox.validate_syntax(target_code)
        if not valid:
            raise ValueError(f"Original code has syntax errors: {error}")
        
        # Evaluate baseline
        baseline_metrics = self._evaluate_code(target_code, utility_function, context or {})
        baseline_utility = baseline_metrics["utility_score"]
        
        logger.info(f"Baseline utility: {baseline_utility:.3f}")
        
        # Initialize candidates with baseline
        candidates = [OptimizationCandidate(
            candidate_id="baseline",
            strategy=strategy,
            code=target_code,
            utility_score=baseline_utility,
            generation=0,
            metadata={"is_baseline": True}
        )]
        
        total_candidates = 1
        best_candidate = candidates[0]
        
        # Run optimization iterations
        for iteration in range(iterations):
            logger.info(f"Iteration {iteration + 1}/{iterations}")
            
            # Generate new candidates based on strategy
            new_candidates = self._generate_candidates(
                candidates,
                utility_function,
                utility_description,
                strategy,
                beam_width,
                context or {},
                iteration + 1
            )
            
            total_candidates += len(new_candidates)
            
            # Select best candidates for next iteration (beam search)
            all_candidates = candidates + new_candidates
            all_candidates.sort(key=lambda c: c.utility_score, reverse=True)
            candidates = all_candidates[:beam_width]
            
            # Track best candidate
            if candidates[0].utility_score > best_candidate.utility_score:
                best_candidate = candidates[0]
                logger.info(f"New best: utility={best_candidate.utility_score:.3f}, improvement={((best_candidate.utility_score - baseline_utility) / baseline_utility * 100):.1f}%")
        
        duration = time.time() - start_time
        improvement = ((best_candidate.utility_score - baseline_utility) / baseline_utility) * 100
        
        # Calculate confidence score
        confidence = self._calculate_confidence(
            best_candidate,
            baseline_utility,
            total_candidates
        )
        
        result = OptimizationResult(
            optimization_id=optimization_id,
            target_function="optimized_function",
            strategy=strategy,
            iterations=iterations,
            candidates_generated=total_candidates,
            best_candidate=best_candidate,
            baseline_utility=baseline_utility,
            improved_utility=best_candidate.utility_score,
            improvement_percent=improvement,
            duration_seconds=duration,
            confidence_score=confidence,
            timestamp=time.time()
        )
        
        # Save result
        self._save_result(result)
        self.optimization_history.append(result)
        
        logger.info(f"Optimization complete: improvement={improvement:.1f}%, confidence={confidence:.3f}, duration={duration:.2f}s")
        
        return result
    
    def _generate_candidates(
        self,
        parent_candidates: List[OptimizationCandidate],
        utility_function: Callable,
        utility_description: str,
        strategy: OptimizationStrategy,
        count: int,
        context: Dict[str, Any],
        generation: int
    ) -> List[OptimizationCandidate]:
        """Generate new candidate improvements"""
        new_candidates = []
        
        # Select parents for improvement
        parents = parent_candidates[:count] if len(parent_candidates) >= count else parent_candidates
        
        for parent in parents:
            try:
                # Generate improved code using LLM
                improved_code = self.llm.generate_improvement(
                    parent.code,
                    utility_description,
                    context,
                    strategy
                )
                
                # Validate syntax
                valid, error = self.sandbox.validate_syntax(improved_code)
                if not valid:
                    logger.warning(f"Generated code has syntax errors: {error}")
                    continue
                
                # Evaluate utility
                metrics = self._evaluate_code(improved_code, utility_function, context)
                utility_score = metrics["utility_score"]
                
                candidate = OptimizationCandidate(
                    candidate_id=f"gen{generation}_{hashlib.md5(improved_code.encode()).hexdigest()[:8]}",
                    strategy=strategy,
                    code=improved_code,
                    utility_score=utility_score,
                    generation=generation,
                    parent_id=parent.candidate_id,
                    metadata=metrics
                )
                
                new_candidates.append(candidate)
                
                logger.debug(f"Generated candidate: utility={utility_score:.3f}, parent={parent.candidate_id}")
                
            except Exception as e:
                logger.error(f"Failed to generate candidate: {e}")
                continue
        
        return new_candidates
    
    def _evaluate_code(
        self,
        code: str,
        utility_function: Callable,
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Evaluate code using utility function"""
        
        # In production, would execute code and measure actual performance
        # For now, use simulated metrics
        
        metrics = {
            "execution_time_ms": 10.0,
            "success_rate": 1.0,
            "tokens_used": 5000,
            "context_efficiency": 0.85,
            "code_lines": len(code.split('\n'))
        }
        
        # Calculate utility using provided function
        utility_score = utility_function(metrics)
        metrics["utility_score"] = utility_score
        
        return metrics
    
    def _calculate_confidence(
        self,
        best_candidate: OptimizationCandidate,
        baseline_utility: float,
        total_candidates: int
    ) -> float:
        """
        Calculate confidence in the optimization
        
        Factors:
        - Magnitude of improvement
        - Number of candidates explored
        - Generation depth
        """
        improvement_factor = (best_candidate.utility_score - baseline_utility) / baseline_utility
        exploration_factor = min(1.0, total_candidates / 50)  # Normalize to 50 candidates
        depth_factor = min(1.0, best_candidate.generation / 5)  # Normalize to 5 generations
        
        confidence = (
            0.5 * improvement_factor +
            0.3 * exploration_factor +
            0.2 * depth_factor
        )
        
        return max(0.0, min(1.0, confidence))
    
    def _save_result(self, result: OptimizationResult):
        """Save optimization result to disk"""
        result_file = self.state_dir / f"{result.optimization_id}.json"
        
        with result_file.open("w") as f:
            json.dump(result.to_dict(), f, indent=2)
        
        logger.debug(f"Saved result to {result_file}")
    
    def load_result(self, optimization_id: str) -> Optional[OptimizationResult]:
        """Load a saved optimization result"""
        result_file = self.state_dir / f"{optimization_id}.json"
        
        if not result_file.exists():
            return None
        
        with result_file.open("r") as f:
            data = json.load(f)
        
        # Reconstruct enums
        data["strategy"] = OptimizationStrategy(data["strategy"])
        data["best_candidate"]["strategy"] = OptimizationStrategy(data["best_candidate"]["strategy"])
        
        # Reconstruct dataclasses
        data["best_candidate"] = OptimizationCandidate(**data["best_candidate"])
        
        return OptimizationResult(**data)
    
    def get_optimization_history(self) -> List[OptimizationResult]:
        """Get history of optimizations"""
        return self.optimization_history


# Convenience function
def optimize_function(
    code: str,
    utility_function: Callable,
    description: str = "Optimize for performance and efficiency",
    strategy: OptimizationStrategy = OptimizationStrategy.BEAM_SEARCH,
    iterations: int = 10
) -> OptimizationResult:
    """
    Convenience function to optimize code using STOP
    
    Usage:
        result = optimize_function(
            code=my_function_code,
            utility_function=lambda m: m["utility_score"],
            description="Optimize for low latency",
            strategy=OptimizationStrategy.BEAM_SEARCH,
            iterations=10
        )
        
        print(f"Improvement: {result.improvement_percent:.1f}%")
        print(f"Best code:\\n{result.best_candidate.code}")
    """
    optimizer = STOPOptimizer()
    return optimizer.optimize(
        target_code=code,
        utility_function=utility_function,
        utility_description=description,
        strategy=strategy,
        iterations=iterations
    )


__all__ = [
    "STOPOptimizer",
    "OptimizationStrategy",
    "OptimizationCandidate",
    "OptimizationResult",
    "LLMInterface",
    "SandboxExecutor",
    "optimize_function"
]

